name: GitHub-Profile-Metrics

on:
  schedule: # 04:00 CST == 20:00 UTC
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_timezone: Asia/Shanghai
          token: ${{ secrets.PERSONAL_PROFILE }}
          plugin_languages: yes
          # plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_display: large
          config_order: isocalendar, languages
