name: GitHub-Profile-Metrics

on:
  schedule: # 04:00 CST == 20:00 UTC
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_timezone: Asia/Shanghai
          filename: profile-metrics.svg
          token: ${{ secrets.PROFILE_METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: html, css, less, dockerfile, makefile, shell, vue, scss, m4
          config_display: large
          config_order: languages
